version: '3.8'

services:
  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    volumes:
      - ./kafka/kafka-config:/opt/kafka/config

  flink:
    build: ./flink
    ports:
      - "8081:8081"
    volumes:
      - ./flink/flink-config:/opt/flink/conf

  spark:
    build: ./spark
    ports:
      - "8080:8080"
    volumes:
      - ./spark/spark-config:/opt/spark/conf

  cassandra:
    build: ./cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra/cassandra-config:/etc/cassandra

  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/elasticsearch-config:/usr/share/elasticsearch/config

  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana-config:/etc/grafana
