global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'flink'
    static_configs:
      - targets: ['flink:8081']

  - job_name: 'spark'
    static_configs:
      - targets: ['spark:8080']
