apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
  template:
    metadata:
      labels:
        app: flink
    spec:
      containers:
      - name: flink
        image: flink:1.10.0
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: flink-config
          mountPath: /opt/flink/conf
      volumes:
      - name: flink-config
        configMap:
          name: flink-config